import { faStar, faChevronUp, faEye, faCompressAlt, faExpandAlt, faSearch, faThumbsDown, faThumbsUp, faArrowLeft, faPlus, faRedo } from '@fortawesome/free-solid-svg-icons';
export const searchIcon = faSearch;
export const thumbsUpIcon = faThumbsUp;
export const thumbsDownIcon = faThumbsDown;
export const arrowLeftIcon = faArrowLeft;
export const plusIcon = faPlus;
export const redoIcon = faRedo;
export const compressAltIcon = faCompressAlt;
export const expandAltIcon = faExpandAlt;
export const eyeIcon = faEye;
export const chevronUpIcon = faChevronUp;
export const starIcon = faStar;